// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rlfm_cpp
Rcpp::List rlfm_cpp(const Rcpp::List& XList, const arma::mat& bmu_int, const arma::mat& A_int, const Rcpp::List& BList_int, const double& nu_int, const arma::mat& LambdaMat_int, const Rcpp::List& SList_f_int, const Rcpp::List& MuList_f_int, const Rcpp::List& SList_h_int, const Rcpp::List& MuList_h_int, const double& epsELBO, const int& maxIter, const bool& verbose, const bool& loop_ic);
RcppExport SEXP _MultiRFM_rlfm_cpp(SEXP XListSEXP, SEXP bmu_intSEXP, SEXP A_intSEXP, SEXP BList_intSEXP, SEXP nu_intSEXP, SEXP LambdaMat_intSEXP, SEXP SList_f_intSEXP, SEXP MuList_f_intSEXP, SEXP SList_h_intSEXP, SEXP MuList_h_intSEXP, SEXP epsELBOSEXP, SEXP maxIterSEXP, SEXP verboseSEXP, SEXP loop_icSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type XList(XListSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type bmu_int(bmu_intSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A_int(A_intSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type BList_int(BList_intSEXP);
    Rcpp::traits::input_parameter< const double& >::type nu_int(nu_intSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type LambdaMat_int(LambdaMat_intSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type SList_f_int(SList_f_intSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type MuList_f_int(MuList_f_intSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type SList_h_int(SList_h_intSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type MuList_h_int(MuList_h_intSEXP);
    Rcpp::traits::input_parameter< const double& >::type epsELBO(epsELBOSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxIter(maxIterSEXP);
    Rcpp::traits::input_parameter< const bool& >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const bool& >::type loop_ic(loop_icSEXP);
    rcpp_result_gen = Rcpp::wrap(rlfm_cpp(XList, bmu_int, A_int, BList_int, nu_int, LambdaMat_int, SList_f_int, MuList_f_int, SList_h_int, MuList_h_int, epsELBO, maxIter, verbose, loop_ic));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MultiRFM_rlfm_cpp", (DL_FUNC) &_MultiRFM_rlfm_cpp, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_MultiRFM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
