# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
#' @noRd
#'
NULL

rlfm_cpp <- function(XList, bmu_int, A_int, BList_int, nu_int, LambdaMat_int, SList_f_int, MuList_f_int, SList_h_int, MuList_h_int, epsELBO, maxIter, verbose, loop_ic = FALSE) {
    .Call(`_MultiRFM_rlfm_cpp`, XList, bmu_int, A_int, BList_int, nu_int, LambdaMat_int, SList_f_int, MuList_f_int, SList_h_int, MuList_h_int, epsELBO, maxIter, verbose, loop_ic)
}

